---
- hosts: localhost
  connection: local
  become: true


  pre_task:
          - name: update repositories
            dnf:
                    update: yes
                    update_cache: yes
                    changed_when: falst
  task:
          - include: task/packages.yml
