---

- hosts: localhost
  connection: local
  become: true

  tasks:
          - name: install packages
            dnf:
                    name:
                            - tmux
                            - mc
                    state: latest
