---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
          - name: update repositories
            ansible.builtin.dnf:
                    update_only: yes
                    update_cache: yes
            changed_when: false
  tasks:
          - ansible.builtin.include_tasks: tasks/packages.yml
          - ansible.builtin.include_tasks: tasks/users.yml
          - ansible.builtin.include_tasks: tasks/cron.yml
