---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
          - name: update repositories
            dnf:
                    update_only: yes
                    update_cache: yes
            changed_when: false
  tasks:
          - include_tasks: tasks/packages.yml
